vim.keymap.set("n", "[d", vim.diagnostic.goto_prev)
vim.keymap.set("n", "]d", vim.diagnostic.goto_next)
vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, { desc = "Open diagnostic" })
vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, { desc = "Set location list" })

vim.keymap.set("n", "<space>t&", function()
  vim.cmd("tabn 1")
end, { desc = "Go to Tab 1" })
vim.keymap.set("n", "<space>té", function()
  vim.cmd("tabn 2")
end, { desc = "Go to Tab 2" })
vim.keymap.set("n", '<space>t"', function()
  vim.cmd("tabn 3")
end, { desc = "Go to Tab 3" })
vim.keymap.set("n", "<space>t'", function()
  vim.cmd("tabn 4")
end, { desc = "Go to Tab 4" })
vim.keymap.set("n", "<space>tn", function()
  vim.cmd("tabnew")
end, { desc = "New tab" })
vim.keymap.set("n", "<space>tc", function()
  vim.cmd("tabclose")
end, { desc = "Close tab" })

vim.keymap.set({ "n", "x" }, "p", "<Plug>(YankyPutAfter)")
vim.keymap.set({ "n", "x" }, "P", "<Plug>(YankyPutBefore)")
vim.keymap.set({ "n", "x" }, "gp", "<Plug>(YankyGPutAfter)")
vim.keymap.set({ "n", "x" }, "gP", "<Plug>(YankyGPutBefore)")

vim.keymap.set("ca", "G", "vert G")
vim.keymap.set("ca", "h", "vert h")
vim.keymap.set("ca", "help", "vert help")

vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })

vim.keymap.set("n", "<leader>cp", ":let @+ = expand('%')<CR>", { desc = "Copy current file path", silent = true })
vim.keymap.set("n", "<leader>dl", function()
  vim.lsp.enable(vim.bo.filetype, false)
end, { desc = "Copy current file path", silent = true })
